spring.application.name=book-service
spring.datasource.url=jdbc:postgresql://localhost:5432/book-store-multi-module
spring.datasource.username=postgres
spring.datasource.password=gmbaloch123$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=QmFzZTY0RW5jb2RlZFNlY3JldEtleUhlcmVEYXRhQmFzZTY0SGVyZQ==